FROM node:22-alpine

LABEL org.opencontainers.image.source="https://github.com/docmost/docmost"

# Install system dependencies
RUN apk add --no-cache curl bash git

# Set working directory
WORKDIR /app

COPY start-dev.sh ./start-dev.sh

# Make the start script executable
RUN chmod +x start-dev.sh

RUN npm install -g pnpm@10.4.0

# Change ownership to node user
# RUN chown -R node:node /app

# Switch to node user
# USER node

# Expose ports for development
# 3000: Server
# 5173: Vite dev server (client)
# 3001: Collaboration server
EXPOSE 3000 5173 3001

# Set environment variables for development
ENV NODE_ENV=development

# Start development server with hot reload
CMD ["bash", "./start-dev.sh"]
